### PR TITLE
fix(#12/#13): using tar instead of zip

### LINKED ISSUE #12: Error on creating new project with the template
Initial issue was raised here: https://github.com/BearStudio/start-ui-native/issues/55

> When I run the command `npx create-start-ui --native start-up-proj`, I get this:
> ```
> ✖ An error occured while unziping template.
> Maybe this folder already exists: /home/obi/src/react-native/tmp/start-up-proj
> If this is the case, try removing it.
> ```

Version used: `0.1.0`

### LINKED ISSUE #13: fail `npx create-start-ui --web myApp` on windows plaform powershell
## using powershell
```powershell

              #%%%
      (#####%%%%%%%%%%%%%%%
    ############%%%%%%%%%%%%%%%#
  #####################%%%%%%%%%%%%
 (((((######################%%%%%%%%%
 ((((((((((                  #####%%%%%
((((((((((                     ########%
(((((((((((                    #########
 ((((((((((                  ###########
 (((((((((                  ((((########
 (((((((                  /(((((((((((##
  ((((((((((((((         ((((((((((((((
   ####(((((((((((      (((((((((((((
     #######((((((((((((((((((((((((
       ###########((((((((((((((((
          #############((((((((
                %#%#########

   ____  _             _     _   _ ___
  / ___|| |_ __ _ _ __| |_  | | | |_ _|
  \___ \| __/ _` | '__| __| | | | || |
   ___) | || (_| | |  | |_  | |_| || |
  |____/ \__\__,_|_|   \__|  \___/|___|

× An error occured while unziping template.
Maybe this folder already exists: E:\WebDev\Projects\myApp
If this is the case, try removing it.
PS E:\WebDev\Projects>
```
image

## using cmd
when I use another terminal `cmd`, it works pefect.

image

### PR DESCRIPTION
**Pull request by yoannfleurydev**
closes #12
closes #13

Checked on Windows Powershell, the problem was mainly because of the partitions, but I still think the tar rewrite was a good thing to be honest.

image

Also tested on MacOS with the new code.

image

### CODE REVIEW

File: utils/generate.js [hunk 1]
```diff
@@ -55,19 +55,43 @@ const generate = async ({ projectName, outDirPath, target }) => {
...
-    spinner.fail(chalk.red('An error occured while unziping template.'));
+    await tar.extract({ file: tempFilePath, cwd: tmpDir });
+    debug('Template extracted');
+  } catch (extractArchiveError) {
+    debug(
+      'An error occured while extracting the template archive.',
+      extractArchiveError
+    );
+    spinner.fail(
+      chalk.red('An error occured while cting the template archive.')
```
Comment (DecampsRenan) [inline utils/generate.js]:
```suggestion
      chalk.red('An error occured while extracting the template archive.')
```
